version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html
    

  db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  cron:
    image: curlimages/curl:latest
    container_name: wordpress_cron
    entrypoint: [ "sh", "-c" ]
    command: |
      "while true; do
         if [ ! -f /var/www/html/scheduler.lock ]; then
           touch /var/www/html/scheduler.lock;
           curl --silent --output /dev/null http://wordpress/wp-content/plugins/auto-content-generator/includes/scheduler.php?doing_wp_cron;
           rm -f /var/www/html/scheduler.lock;
         fi;
         sleep 60; 
       done"
    depends_on:
      - wordpress
    volumes:
    - ./wordpress:/var/www/html
volumes:
  db_data:
